debug = false

defaultEntryPoints = ["https","http"]

[log]
  level = "INFO"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[docker]

[retry]

[api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false
  watch = true

[certificatesResolvers.basic.acme]
  storage = "acme/certs.json"
  [certificatesResolvers.basic.acme.httpChallenge]
    entryPoint = "http"
