# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:  
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    # Runs a set of commands using the runners shell
    - name: Setup .env
      run: cp .env.example .env

    - name: Docker start
      run: docker-compose up -d mass mass-db

    - name: Debug
      run: docker exec mass id
    - name: Debug
      run: docker exec mass ls -a 

    - name: Initialize app
      run: docker exec mass composer initialize
